# Generated by Django 3.2.4 on 2021-06-05 03:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penny', models.IntegerField(default=0)),
                ('nickel', models.IntegerField(default=0)),
                ('dime', models.IntegerField(default=0)),
                ('quarter', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('coke', models.IntegerField(default=0)),
                ('pepsi', models.IntegerField(default=0)),
                ('soda', models.IntegerField(default=0)),
                ('money', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.money')),
            ],
        ),
    ]
