# Generated by Django 3.2.4 on 2021-06-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='total',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
