# Generated by Django 3.2.4 on 2021-06-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210605_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
