# Generated by Django 3.2.4 on 2021-06-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='billed_amount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
